project:
  type: website
  output-dir: docs

website:
  title: "Simon’s Green Corner"
  logo: images/logo.png
  navbar:
    right:
      - href: index.qmd
        text: Strona główna
      - href: plants/carnivorous.qmd
        text: Rośliny owadożerne
      - href: plants/index.qmd
        text: Wszystkie rośliny

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pl