project:
  type: website
  output-dir: docs
  resources:
    - images/

website:
  title: "Simon's Green Corner"
  navbar:
    title: false
    logo: images/logo.png
    logo-alt: "Simon's Green Corner"
    right:
      - href: index.qmd
        text: Strona główna
      - href: categories/index.qmd
        text: Kategorie
      - href: plants/index.qmd
        text: Wszystkie rośliny

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: pl